# Generated by Django 5.2.9 on 2026-08-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_factura_descuento_factura_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
