# Generated by Django 6.1 on 2026-08-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_cliente_id_alter_factura_id'),
        ('facturacion', '0006_alter_factura_usuario'),
    ]

    operations = [
    ]
