# Generated by Django 5.2.9 on 2026-08-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0007_merge_20260813_2017'),
        ('facturacion', '0007_merge_20260813_2022'),
    ]

    operations = [
    ]
