# Generated by Django 6.1 on 2026-08-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_alter_cliente_id_alter_factura_id'),
        ('facturacion', '0009_alter_detallefactura_id'),
    ]

    operations = [
    ]
