# Generated by Django 6.1 on 2026-08-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_merge_20260820_1300'),
        ('facturacion', '0010_merge_20260820_1306'),
    ]

    operations = [
    ]
