# Generated by Django 5.2.9 on 2026-08-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0011_merge_20260820_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
