# Generated by Django 5.2.9 on 2026-08-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_alter_cliente_id_alter_factura_id'),
        ('facturacion', '0012_alter_detallefactura_id'),
    ]

    operations = [
    ]
