# Generated by Django 6.0.6 on 2026-06-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
