# Generated by Django 6.0.6 on 2026-06-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='resultado',
            new_name='total',
        ),
    ]
