# Generated by Django 6.0.6 on 2026-07-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_resultado_producto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='total',
        ),
    ]
