# Generated by Django 5.2.9 on 2026-08-20 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_producto_precio_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser mayor que cero.')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Debe haber minimo un producto en el stock')]),
        ),
    ]
