# Generated by Django 5.2.9 on 2026-08-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_producto_id_alter_producto_stock'),
        ('productos', '0012_alter_producto_stock'),
    ]

    operations = [
    ]
