# Generated by Django 6.1 on 2026-09-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_merge_20260820_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Frenos', 'Frenos'), ('Motor', 'Motor'), ('Transmisión', 'Transmisión'), ('Lubricantes y Fluidos', 'Lubricantes y Fluidos'), ('Suspensión', 'Suspensión'), ('Eléctrico', 'Eléctrico'), ('Llantas y Ruedas', 'Llantas y Ruedas'), ('Dirección', 'Dirección'), ('Carrocería', 'Carrocería'), ('Accesorios', 'Accesorios'), ('Filtros', 'Filtros'), ('Repuestos Generales', 'Repuestos Generales'), ('Insumos de Taller', 'Insumos de Taller')], max_length=100),
        ),
    ]
