# Generated by Django 5.2.9 on 2026-08-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_alter_empresaconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
