# Generated by Django 6.0.6 on 2026-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_alter_empresaconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
