# Generated by Django 6.0.6 on 2026-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(choices=[('SuperAdmin', 'SUPERADMIN'), ('Admin', 'ADMIN'), ('Empleado', 'EMPLEADO')], default='Empleado', max_length=15),
        ),
    ]
