# Generated by Django 6.0.6 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
