# Generated by Django 6.1 on 2026-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_usuarios_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(choices=[('SuperAdmin', 'SUPERADMIN'), ('Admin', 'ADMIN'), ('Empleado', 'EMPLEADO')], default='Empleado', max_length=15, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contra',
            field=models.CharField(max_length=15, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del empleado'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Teléfono'),
        ),
    ]
