# Generated by Django 6.1 on 2026-08-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuarios_activo_alter_usuarios_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='documento',
            field=models.CharField(default='SIN DOCUMENTO', max_length=15, verbose_name='Documento de identidad'),
            preserve_default=False,
        ),
    ]
