# Generated by Django 6.0.6 on 2026-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(choices=[('USUARIOS', 'Usuarios'), ('PRODUCTOS', 'Productos'), ('INVENTARIO', 'Inventario'), ('FACTURACION', 'Facturación'), ('CONFIGURACION', 'Configuración')], max_length=100),
        ),
    ]
