# Generated by Django 6.1 on 2026-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_alter_auditoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='modulo',
            field=models.CharField(choices=[('USUARIOS', 'Usuarios'), ('PRODUCTOS', 'Productos'), ('INVENTARIO', 'Inventario'), ('FACTURACION', 'Facturación'), ('FINANZAS', 'Finanzas'), ('CONFIGURACION', 'Configuración')], max_length=100),
        ),
    ]
